import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header';
import { LeftMenu } from '@/components/leftMenu';
import { BottomMenu } from '@/components/bottomMenu';

export const metadata: Metadata = {
  title: 'Everythings',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <LeftMenu />
        <Header />
        {children}
        <BottomMenu />
      </body>
    </html>
  );
}
